export default {
  color: {
    alpys_background: '#fcfcfc',
    alpys_tx_title: '#D45C05',
    alpys_tx_text: '#582F04',
    alpys_bg_input: '#DCCBBF',
    alpys_tx_input: '#582F04',
    alpys_bg_block: '#582F04',
    alpys_placeholder_input: '#A07C7C',
    alpys_border_block: '#D45C05',
    alpys_bg_button: '#048fc9',
    alpys_tx_button: '#FFFFFF',
    alpys_bg_submit: '#D45C05',
    alpys_tx_submit: '#FFFFFF',
    alpys_bg_apple: '#ffffff',
    alpys_tx_apple: '#000000',
    alpys_bg_google: '#048fc9',
    alpys_tx_google: '#ffffff',
    alpys_sucess: '#03A877',
    alpys_edit: '#0377A8',
    alpys_error: '#aa0000',
    tabBarActiveTintColor: '#D45C05',
    tabBarActiveBackgroundColor: '#fcfcfc',
    tabBarInactiveTintColor: '#A07C7C',
    tabBarStyle_bg: '#fcfcfc',
    tabBarStyle_border: '#D45C05',
    headerTintColor:'#D45C05',
    alpys_switch_track_false: '#DCCBBF',
    alpys_switch_track_true: '#DCCBBF',
    alpys_switch_thumb_true: '#D45C05',
    alpys_switch_thumb_false: '#ffffff',
  }
}